### ISSUE TITLE
Using Outbox results in multi-subscriber events being processed by only one subscriber

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.RavenDB#111]
While fixing https://github.com/Particular/NServiceBus.NHibernate/issues/117 it was determined that RavenDB has a similar problem.

Task force: @bording @davidboike

### Who's affected
To be affected by this bug, you must be using the Outbox feature for message deduplication with RavenDB persistence, and publish events to multiple subscribers. In addition, endpoints must be configured to use a shared Raven database for persistence, which is a non-default implementation.

### Symptoms
An event is published for multiple subscribers, but only one subscriber successfully receives and processes the message. Other subscribers may receive the event and attempt to process it, but are unable to do so.

### Impact assessment
Customer must be using RavenDB + Outbox + shared database for persistence + publishing multi-subscriber events. With the shared database configuration being non-default, this is likely not a typical configuration.

### Customer communication
We have discovered a bug with the RavenDB implementation of the Outbox feature. Although the intersection of features necessary for this bug to present itself (RavenDB + Outbox + shared database for persistence + publishing multi-subscriber events) makes its overall impact fairly small, we are still taking this quite seriously as, for those customers that are affected, it effectively leads to message loss.

### Plan of Attack
- [x] Determine best approach to conditionally load multiple documents (`Load()` vs. `LoadStartingWith()`)
- [x] Update NSB.Raven 3.0 as hotfix on master
- [x] Backport to support-2.2 branch
- [x] Release
- [x]  GG Announcement

**Comment by andreasohlund** [comment]
@bording took the liberty to move this to `Getting ready` since we're clearly going ahead with this. Please move to `In progress` when you start implementing it
