### ISSUE TITLE
Relax version constraints between client and server

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.RavenDB#117]
> When it comes to client server compatibility in RavenDB there are two valid rules. Either:

> * The server version is within the same Major and Minor range as the client version

> OR

> * The server version is greater than the client version

> Some examples:

> * 2.5 client will work with 3.0 server since server is greater than client
> * 2.5 client will work with 2.5 server since client and server are in the same Major and Minor range
> * 3.0.3785 client will work with 3.0.3528 server since client and server are in the same Major and Minor range
> * 2.5 client will NOT work with 2.0 server since client is greater than server
> * 3.0 client will NOT work with 2.5 server since client is greater than server

http://ravendb.net/docs/article-page/3.0/csharp/client-api/faq/backward-compatibility

But we hardcode to a specific range

https://github.com/Particular/NServiceBus.RavenDB/blob/support-1.0/src/NServiceBus.RavenDB/ConfigureRavenPersistence.cs#L400

https://github.com/Particular/NServiceBus.RavenDB/blob/support-2.2/src/NServiceBus.RavenDB/Internal/ConnectionVerifier.cs#L103

Related discussion

https://groups.google.com/forum/#!topic/particularsoftware/xrzBdkRrPTo

I know we had bad experience in the past regarding client and server compatibility. But since there is now this documentation page I think we should comply to that and not restrict our clients from using an officially supported version pair.

@Particular/nservicebus @Particular/guidance-support thoughts?

**Comment by andreasohlund** [comment]
@johnsimons I remember we had to restrict some versions since the raven dtc support was broken?

**Comment by danielmarbach** [comment]
@mauroservienti confirmed on a call today that it was because of the broken DTC support

**Comment by johnsimons** [comment]
@danielmarbach from my experience I would just state that the server version needs to be higher or equal to the client, even from patches. So if client is 1.1.1234 the server has to be either 1.1.1234 or greater.

**Comment by SimonCropp** [comment]
> from my experience I would just state that the server version needs to be higher or equal to the client, even from patches

@johnsimons that would be a raven bug that should be passed to ayende not handle by us

**Comment by danielmarbach** [comment]
I relaxed the version constraints for the user in version 1.0.3 because it was a simple fix. I don't think it makes sense to backport it to all versions. Thoughts?

**Comment by danielmarbach** [comment]
@mauroservienti see the full history here

**Comment by danielmarbach** [comment]
Fixed and backported to 1.0.3 and 2.2.4
