### ISSUE TITLE
Subscription documents per message type & endpoint

### ISSUE THREAD

**Issue by colin-higgins** [Particular/NServiceBus.RavenDB#125]
Split out the subscription mega-document into individual documents per message type and logical endpoint.
Pull request: https://github.com/Particular/NServiceBus.RavenDB/pull/129

#### Goals: 
- Reduce contention
- Improve write/read speed

#### Plan:
- [ ] Convert `SubscriptionPersister` to write documents per message type and endpoint
  - - [ ] Only convert those entries which belong to the endpoint
- [ ] On startup, check flag for whether we should convert to new schema. Use the corresponding schema.
- [ ]  If using the new schema, on startup in new endpoint, check for items in legacy document format and convert to individual documents
- [ ] Write tests
  - - [ ] Saving new subscriptions successful
  - - [ ] Converting old subscriptions successful
  - - [ ] Reading subscriptions from old version into old class successful
  - - [ ] Reading subscriptions from new version into new class successful

Use an opt-out method for upgrading to the new schema. If the user has specified an app setting to not upgrade their schema, use the old method of persisting.

cc / @mauroservienti @DavidBoike

**Comment by mauroservienti** [comment]
What concerns me the most is backward compatibility, if any is needed. We are forcing the user to migrate to RavenDB 3.0 at the server level that mean that we cannot face any scenario where a RavenDB v2.x based endpoint is talking to a new one, so we are sure all endpoints looking at subscriptions are using the new RavenDB package.

The above means that at endpoint startup we can check if the database contains some legacy subscription format documents and upgrade them on the fly to the new format,

The thing we need to take into account is that we may have multiple instances of the same endpoint starting up at the same time and we should avoid upgrade concurrency issues.

@colin-higgins @DavidBoike Am I missing something obvious?

**Comment by mauroservienti** [comment]
I'm wrong: http://ravendb.net/docs/article-page/3.0/csharp/client-api/faq/backward-compatibility

**Comment by colin-higgins** [comment]
As a task force, we decided that this would not add enough value to justify complicating the v6 release.

**Comment by DavidBoike** [comment]
So let's close, label with one of the withdrawns?

**Comment by mauroservienti** [comment]
`Won't fix` seems to be a good option, we can revisit it later.

> --
Mauro Servienti | Solution Architect | Particular Software
