### ISSUE TITLE
Validate if an custom DocumentStore instance has the default resource manager id set

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.RavenDB#126]
We allow customers to create their own `DocumentStore` session. When we create our own we make sure that the resource manager id value gets a deterministic id based on the endpoint name and its version.

We can validate if the given custom `DocumentStore` instance has the default value for the resource manager id set which is `E749BAA6-6F76-4EEF-A069-40A4378954F8` and log a warning.

References
- https://github.com/ravendb/ravendb/blob/master/Raven.Client.Lightweight/Document/DocumentStore.cs#L127

**Comment by colin-higgins** [comment]
@mauroservienti @DavidBoike @kbaley 
Should this definitely be in v6? It's not a breaking change, and could be deferred, but it seems like an easy win.

**Comment by kbaley** [comment]
In my experience, it's best to be very draconian about allowing things to creep in, even if it's "just a couple of days" worth of work. It adds up and sets precedents.

**Comment by DavidBoike** [comment]
I'm already fixing this for V3 in #136 as a bug, and it wouldn't sense not to pull it in for V6 at that point. So I'm going to close this in favor of #136.
