### ISSUE TITLE
Specify Connection String with Code

### ISSUE THREAD

**Issue by colin-higgins** [Particular/NServiceBus.RavenDB#128]
Right now we only support setting the connection string through app settings `NServiceBus/Persistence/RavenDB`, or if the user passes us their own document session. 

Letting the user pass in a connection string might reduce the number of users who need to pass in a document session, thus reducing the complexity they need to manage and subsequently, our support load. 

It would also simplify configuration management because users could consolidate configuration for the raven connection string.

Justifications:
- matching other persistences/transports 
- multi-endpoint hosting

**Comment by ramonsmits** [comment]
Having the following configuration options would help:

* `.UseConnectionString(string)`
* `.UseConnectionStringName(string)`

That would make the RavenDB package more aligned with all the other packages that support connection strings and prevents the user from having to create a custom `DocumentStore` and set the `ConnectionStringName` property.

**Comment by weralabaj** [comment]
@Particular/ravendb-persistence-maintainers would that be a good proposition for RC?

**Comment by DavidBoike** [comment]
Since we're trying to get people to provide a fully configured DocumentStore so that the DTC settings can be configured correctly, I don't think we should make it any easier to use a connection string.

I would vote to close this as Won't Fix.

**Comment by SimonCropp** [comment]
+1 to what David said

**Comment by mauroservienti** [comment]
As noted during the PladDev sync this is missing a label. Added.
