### ISSUE TITLE
Determine what to do with TransactionRecoveryStorage settings

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.RavenDB#136]
Related to #122 

Had a conversation with Oren about transaction-related settings. Here are some notes/observations:

* Our approach to generating ResourceManagerId is good.
* For TransactionRecoveryStorage, we should always use LocalDirectoryTransactionRecoveryStorage. Storage location can be in AppLocal directory based on endpoint name convention.

Our users should never have to use or think about these settings. Currently in 3.0.x they have to provide their own DocumentStore and set both of these settings themselves to escape from IsolatedStorageTransactionRecoveryStorage, which Oren says you should only use if you want to generate race conditions.

We can provide a method to customize the DocStore after NServiceBus is done messing with it and before Initialize() is called on it, for the people who really want to override something, who will then be on their own.

Based on this, I no longer think of this as a feature that should be introduced only with must-be-async Core V6. This is a bug that needs to be fixed as either NSB.RavenDB 3.1.0, or perhaps 3.0.6. I would prefer 3.1.0 (I think) because it's a definite behavior change. I'm not even sure if releasing 3.1.0 is possible now that develop has started the march toward 4.0.0.

Thoughts @Particular/engineers ?

## Plan of Attack

* [x] Fix code
  * [x] Enforce proper ResourceManagerId / TxRecoveryStorage options regardless of source of DocStore
    * ResourceManagerId with same strategy as now, but just universally
    * TxRecoveryStorage as LocalDirectory, specifying location in AppLocal that includes the ResourceManagerId, as that value already encapsulates a machine-unique value.
  * [x] If non-default value is detected for either, warn user that we are overwriting
  * [x] Provide API to modify DocStore *after* NServiceBus is done with it (get out of jail free card) and make sure overwrite warnings point to that API
* [x] Update doco article as WIP: http://docs.particular.net/nservicebus/ravendb/ Particular/docs.particular.net#1137
* [x] Release & Merge Doco
* [ ] Announcement
* [ ] Incorporate in develop for CoreV6 #176

## Who's affected

Any customer using NServiceBus.RavenDB 3.0.x is affected by this bug and should upgrade in order to get smarter handling of RavenDB transaction settings.

## Symptoms

Under high load, you may get IsloatedStorage-related exceptions, such as the one shown below. Successfully working around these requires providing a custom `DocumentStore` for NServiceBus to use (ignoring NServiceBus's ability to auto-create it) and then specifying LocalDirectoryTransactionRecoveryStorage.

```
2016-01-04 09:25:41.241 INFO  NServiceBus.Unicast.Transport.TransportReceiver Failed to process message
System.Transactions.TransactionAbortedException: The transaction has aborted. ---> System.IO.IsolatedStorage.IsolatedStorageException: Unable to create mutex. (Exception from HRESULT: 0x80131464)
   at System.IO.IsolatedStorage.IsolatedStorageFile.Open(String infoFile, String syncName)
   at System.IO.IsolatedStorage.IsolatedStorageFile.Lock(Boolean& locked)
   at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
   at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, IsolatedStorageFile isf)
   at System.IO.IsolatedStorage.IsolatedStorageFile.CreateFile(String path)
   at Raven.Client.Document.DTC.IsolatedStorageTransactionRecoveryContext.CreateFile(String name, Action`1 createFile) in c:\Builds\RavenDB-3.0-Unstable\Raven.Client.Lightweight\Document\DTC\IsolatedStorageTransactionRecoveryContext.cs:line 22
   at Raven.Client.Document.RavenClientEnlistment.Prepare(PreparingEnlistment preparingEnlistment) in c:\Builds\RavenDB-3.0-Unstable\Raven.Client.Lightweight\Document\RavenClientEnlistment.cs:line 65
   --- End of inner exception stack trace ---
   at System.Transactions.TransactionStatePromotedAborted.PromotedTransactionOutcome(InternalTransaction tx)
   at System.Transactions.CommittableTransaction.Commit()
   at System.Transactions.TransactionScope.InternalDispose()
   at System.Transactions.TransactionScope.Dispose()
   at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 306
```

**Comment by DavidBoike** [comment]
Also ping @Particular/tf-async-persistence

**Comment by SimonCropp** [comment]
To me this sounds like a bug in ravendb that we are being forced to apply a very ugly hack to work around

**Comment by DavidBoike** [comment]
No argument.

**Comment by SimonCropp** [comment]
i would prefer to just log a warning. messing with the state of a passed in DocumentStore  should be avoided

**Comment by DavidBoike** [comment]
Now I disagree. Everything we have right now is broken. Only way to get it right is to supply your own DocStore (even if you want to use default localhost / endpoint name db) and then specify the secret handshake properties just right. We shouldn't expect this kind of intimate knowledge of Raven from our users.

Also, we're *already* messing with the DocStore, we're just doing it wrong. I'm not saying we start messing, I'm saying the messing we're doing should be done correctly.

**Comment by mauroservienti** [comment]
I agree with @DavidBoike, even if I consider this a bug in RavenDB in light of `making developers better` and `safe by default` we need to fix it and make sure the endpoint works correctly. The only other thing I would find acceptable is that:

* If DTC in `BusConfiguration` is disabled we can skip any fix attempt.
* if the user has already set the `TransactionRecoveryStorage` to other than `IsolatedStorageTransactionRecoveryStorage` we can skip fixing it logging the value found.
* If users are setting up their own DocStore, DTC is enabled and `TransactionRecoveryStorage` is set to the default value of `IsolatedStorageTransactionRecoveryStorage`, that we know to be unsafe, throw and shutdown the endpoint.

Logging a warning in my opinion is not enough, the risk here is message/information loss, and is very likely to happen. We cannot let an endpoint run in those conditions.

**Comment by mauroservienti** [comment]
I like the PoA @DavidBoike. Only thing I'd change is:

> TxRecoveryStorage as LocalDirectory, specifying location in AppLocal that includes endpoint name in convention

given that in some environments it may happen that for testing purpose multiple endpoints are run on the same machine we should use to generate the unique path to use for the TxRecoveryStorage including the resource manager id that we know is going to be unique per endpoint.

**Comment by DavidBoike** [comment]
Changed the PoA to just use the ResourceManagerId for the path in TxRecoveryStorage.

**Comment by DavidBoike** [comment]
PR #143 is ready for review

**Comment by andreasohlund** [comment]
@Particular/persistence-maintainers can we move this one into `In-progress`?

also why is there a `core v6` label on?

**Comment by DavidBoike** [comment]
It is in progress. I've been working on it. Added the label.

Whatever the code for 3.1 (now 3.1.1) needs to be included in V6 as well. That's why I added the label.

**Comment by andreasohlund** [comment]
>That's why I added the label.

Fair enough!

Can you add the milestone?

**Comment by mikeminutillo** [comment]
@DavidBoike is the Plan of Attack up to date on this issue? According to the PoA, all that is left to do is the Announcement (which is [here](https://github.com/Particular/Announcements/issues/76)) and the v6 changes (which are [here](https://github.com/Particular/NServiceBus.RavenDB/pull/176)). What other action is needed to close this issue? Given that those other things are represented by issues, does it make sense to close this one?

**Comment by DavidBoike** [comment]
What we're going to do about Raven is very much in the air at present.

**Comment by danielmarbach** [comment]
Since https://github.com/Particular/PlatformDevelopment/issues/686 is tracking transaction work I'm removing the V6 label for now.

**Comment by andreasohlund** [comment]
Should we treat this one as critical? or move it into the backlog?

**Comment by mauroservienti** [comment]
@DavidBoike @colin-higgins since this is linked to V4.0.0 should we consider https://github.com/Particular/NServiceBus.RavenDB/pull/166 part of this effort?

**Comment by DavidBoike** [comment]
Commented on #166 when I closed it.

This issue is a bit in limbo at the moment, unfortunately. Removing the 4.0 milestone.

**Comment by DavidBoike** [comment]
Culminating in 3.0.10 (and backports) we concluded to do nothing and push it to the users.
