### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by synhershko** [Particular/NServiceBus.RavenDB#15]
This issue is to track all tests that we commented out or removed from the core but need to run in the RavenDB scope. Some were targeted to RavenDB persistence but should be generalized to be used by more persistence solutions

* [ ] https://github.com/Particular/NServiceBus/tree/develop/src/NServiceBus.Core.Tests/Timeout
* [ ] https://github.com/Particular/NServiceBus/commit/f3281a1ef1d4573279e403946f1e7ecd132be833
* [ ] https://github.com/Particular/NServiceBus/commit/80f107c6f9be4500ce22d12f8d4150ba4ca4e0f3
* [ ] https://github.com/Particular/NServiceBus/commit/014beb03b47cbc60b6f07a881a26d637c2ab0c4f

**Comment by danielmarbach** [comment]
Can anyone update me on this one. I'm missing context. Is this still necessary?

**Comment by synhershko** [comment]
When we ported the code over (extracted from core) there were some tests that got left behind. If you feel comfortable with the coverage, and the scenarios in tests listed here are already covered, this can be closed.

**Comment by danielmarbach** [comment]
Closing this one. Coverage is OK.
