### ISSUE TITLE
LocalDirectoryTransactionRecoveryStorage fails if no access to %LOCALAPPDATA%

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.RavenDB#162]
From [Google group posting](https://groups.google.com/forum/#!topic/particularsoftware/L6nZmyozDbw).

If %LOCALAPPDATA% is not accessible then RavenDB persistence will fail. Customer theorizes that directory will never exist because they are running via IIS as an Active Directory service account.

This bug is a continuation of #136 and will be fixed as continuing work on that issue. 

## Recommendation

This bug affects NServiceBus.RavenDB 3.1.0 only. The package has been unlisted pending a fix. Any user using 3.1.0 in the meantime should downgrade to 3.0.6.

## Workaround

A different choice for TransactionRecoveryStorage can be chosen via the CustomizeDocumentStore option:

This would set it back to the default IsolatedStorage option used with NServiceBus.RavenDB 3.0.x:
```
busConfiguration.UsePersistence<RavenDBPersistence>()
    .CustomizeDocumentStore(store => 
    {
        var docStore = store as DocumentStore;
        docStore.TransactionRecoveryStorage = new IsolatedStorageTransactionRecoveryStorage();
    });
````

Or, select a different directory for transaction recovery storage:
```
busConfiguration.UsePersistence<RavenDBPersistence>()
    .CustomizeDocumentStore(store => 
    {
        var docStore = store as DocumentStore;
        docStore.TransactionRecoveryStorage = 
            new LocalDirectoryTransactionRecoveryStorage(alternatePath);
    });
````

**Comment by mauroservienti** [comment]
as discussed this morning during the weekly sync, in light of `safe by default` this is a critical bug that may involve data/message loss. We need to get this going.

/cc @DavidBoike

**Comment by DavidBoike** [comment]
As finishing this bug (and releasing 3.1.1) is wholly contained within #136 I'm closing this issue. There's no need for duplicate issue tracking the same thing.
