### ISSUE TITLE
Unable to deserialize SagaUniqueIdentity in NServiceBus.RavenDB package when migrating from NServiceBus version 4

### ISSUE THREAD

**Issue by janovesk** [Particular/NServiceBus.RavenDB#188]
## Description

SagaUniqueIdentity was changed from `NServiceBus.Persistence.Raven.SagaPersister.SagaUniqueIdentity, NServiceBus.Core` to `NServiceBus.RavenDB.Persistence.SagaPersister, NServiceBus.RavenDB` when Raven support was moved into its own package. This is problematic because RavenDB stores the CLR-type as part of the metadata on documents. If a saga with a unique property was stored with the internal raven support in core, it blows up if it is loaded from the code in the external package. The following error is thrown by the raven client library:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'NServiceBus.Persistence.Raven.SagaPersister.SagaUniqueIdentity' to type 'NServiceBus.RavenDB.Persistence.SagaPersister.SagaUniqueIdentity'.
   at Raven.Client.Document.InMemoryDocumentSessionOperations.TrackEntity[T](JsonDocument documentFound)
   at Raven.Client.Document.SessionOperations.MultiLoadOperation.<Complete>b__4[T](JsonDocument document)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
  at Raven.Client.Document.SessionOperations.MultiLoadOperation.Complete[T]()
   at Raven.Client.Document.MultiLoaderWithInclude`1.Load[TResult](String id)
   at NServiceBus.RavenDB.Persistence.SagaPersister.RavenSagaPersister.GetByUniqueProperty[T](String property, Object value) in
 ```

## Who's affected

Customers who meet all of the following conditions:

* Customers migrating from the internal Raven support in NServiceBus 4/Raven Server 2.0 to any version of the external package(Raven Server 2.5 or 3)
* Customers who are also using Sagas and their implementation of `IContainSagaData` utilizes the `Unique` attribute

## Symptoms

On of the following exceptions is thrown while processing a Saga:

*For NServiceBus.RavenDb version 1.x*

```
NServiceBus throws "System.InvalidCastException: Unable to cast object of type 'NServiceBus.Persistence.Raven.SagaPersister.SagaUniqueIdentity' to type 'NServiceBus.RavenDB.Persistence.SagaPersister.SagaUniqueIdentity'" when a saga created by internal Raven code is loaded by the external Raven package.
```

*For later versions of NServiceBus.RavenDb*

```
Raven.Abstractions.Exceptions.ConcurrencyException : PUT attempted on document '{sagaid}' using a non current etag (document deleted)
```

## Steps to reproduce

1. Start a console project
2. Install any version NServiceBus using the internal RavenDB support. For example 4.7.12
3. Install RavenDB Server 2.0
4. Add a saga with a unique attribute and store using RavenDB saga persister (Use [Sample20](https://github.com/Particular/Raven188Repro/tree/master/src/Sample20))
5. Upgrade RavenDB Server from 2.0 to 2.5(or 3)
6. Update to use the external RavenDB package. For example RavenDB 1.0.3/2.2.4 for Raven Server 2.5 or 3.0.6 for Raven Server 3.0
7. Load the saga created in 4 (Use [Sample25](https://github.com/Particular/Raven188Repro/tree/master/src/Sample25))
8. Throws 
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'NServiceBus.Persistence.Raven.SagaPersister.SagaUniqueIdentity' to type 'NServiceBus.RavenDB.Persistence.SagaPersister.SagaUniqueIdentity'.`
```

Reproduced on NServiceBus 4.6.10 to 4.7.12 with NServiceBus.RavenDB 1.0.3.

Connects to https://github.com/Particular/PlatformDevelopment/issues/728

**Comment by johnsimons** [comment]
Fixed as part of:
- #204
- #201 
- #203
