### ISSUE TITLE
why is ISagaPersister InstancePerCall?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RavenDB#212]

**Comment by colin-higgins** [comment]
It looks like there was some stateful stuff going on in older versions of SagaPersister.
As of now, yes it seems like it can be moved to single instance without any issue.
I'm interested to see how much of an impact this has in performance tests.

**Comment by SimonCropp** [comment]
@colin-higgins the perf dif will not really be measurable. slightly less CG pressure, but in the scope of everything else happening it will not be noticeable

**Comment by colin-higgins** [comment]
Okay, because it seemed like it was a big deal based on the conversation.

**Comment by SimonCropp** [comment]
it is more about what InstancePerCall implies. and in this case is it implying the wrong thing
