### ISSUE TITLE
Notify users that default document convention changed in 3.0.8

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.RavenDB#222]
We changed the default document conventions in this patch, but did not mention this in the release notes or the announcement. Since some users may have tools that rely on our prior convention to function (e.g. saga renaming) and it may not be clear why the tool is failing. This was discovered while updating the sample.

**Comment by DavidBoike** [comment]
We switched back to the Raven default conventions by default in 3.0.10. No matter what, existing databases will continue to use whatever conventions were started for it, with no intervention required by the user.
