### ISSUE TITLE
Integrate component tests developed for AzureStoragePersistence

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.RavenDB#242]
Related to https://github.com/Particular/NServiceBus/issues/3362

See [Azure Storage Persistence component tests](https://github.com/Particular/NServiceBus.Persistence.AzureStorage/tree/develop/src/NServiceBus.Persistence.AzureStorage.ComponentTests)

**Comment by weralabaj** [comment]
@Particular/ravendb-persistence-maintainers Would that be a good task for me to get more familiar with RavenDB?

@DavidBoike Is that only for Core V6?

Timing-wise is that expected to be done for RC?

**Comment by mauroservienti** [comment]
> Would that be a good task for me to get more familiar with RavenDB?

yeah, I like it. Good idea.

**Comment by DavidBoike** [comment]
Yes, only V6, and in time for RC is not necessary.

**Comment by danielmarbach** [comment]
As part of creating the Service Fabric Persistence we created component tests for sagas, outbox and synchronized storage. The tests have been adopted by MongoDB as well. Closing this since those tests would be a better fit.
