### ISSUE TITLE
Make timeout query implementations consistent

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.RavenDB#252]
As [noted](https://github.com/Particular/PlatformDevelopment/issues/852) by @bording Persistence GetNextChunk is not consistent across different persistence engines and not always across different versions of the same epersistence engine.

we need to be sure that the next release is consistent with the actual production one and aligned with decisions made by other different persistence engines.

**Comment by DavidBoike** [comment]
Consistent methodology should be:

* Stream query
* time > startSlice
* time <= now

Version Implementations:

* 3.0.12 will properly implement this with #299, [specifically here](https://github.com/Particular/NServiceBus.RavenDB/pull/299/files#diff-c8368d1abc20d3a45ec40d8b4e39f0ffR58)
* 4.0.0 [is already conforming](https://github.com/Particular/NServiceBus.RavenDB/blob/4.0.0/src/NServiceBus.RavenDB/Timeouts/QueryTimeouts.cs#L95-L99)
* 2.2.8 is doing stream query but only > startSlice, no <= now or extra query (similar to 3.0.11) - Should we backport #299 there?

**Comment by DavidBoike** [comment]
Maintainers group decided not to backport to V2, as it's not supported (by association to major version) and the "fix" is nowhere near critical.
