### ISSUE TITLE
Usage of DisableInMemoryIndexing = true in OutboxRecordsIndex

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus.RavenDB#257]
I am referring to https://github.com/Particular/NServiceBus.RavenDB/blob/b5283792519a8d3fa2d18c487f8b062c5e63ad94/src/NServiceBus.RavenDB/Outbox/OutboxRecordsIndex.cs#L18

I am not sure I would advice to have that setting on.

We have that on in ServiceControl, but ServiceControl is a different beast. For the outbox I would not do that and instead use the defaults.

**Comment by DavidBoike** [comment]
I disagree, I think the usage for OutboxRecordsIndex is correct. There's no advantage to keeping the index around in memory, as all critical path operations that happen with messages do a load by id. The index is only needed 7 days later to delete the expired items.

It's actually kind of interesting that we don't use the Expiration bundle for this, although then we'd have to programmatically require the Expiration bundle in a database we don't necessarily own.

This does raise the question of why we need to index `MessageId` and `Dispatched` when DispatchedAt is all that's needed.

**Comment by johnsimons** [comment]
> There's no advantage to keeping the index around in memory, as all critical path operations that happen with messages do a load by id. The index is only needed 7 days later to delete the expired items.

That is a good reason, thanks for clarifying

> It's actually kind of interesting that we don't use the Expiration bundle for this, although then we'd have to programmatically require the Expiration bundle in a database we don't necessarily own.

Don't go there, expiration bundle is no go


> This does raise the question of why we need to index MessageId and Dispatched when DispatchedAt is all that's needed.

if it is not needed then don't do it
