### ISSUE TITLE
Outbox settings code API - improve & align with NHibernate

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus.RavenDB#262]
The current API as presented in http://docs.particular.net/nservicebus/nhibernate/outbox and http://docs.particular.net/nservicebus/ravendb/outbox.
- Would be better as the extension method on `.UsePersistence<RavenDB>` rather then `EndpointConfiguration`.
- Method names don't indicate it's related to outbox, especially that we also have Gateway deduplication records, proposition `SetTimeToKeepOutboxDeduplicationData` and `SetFrequencyToRunOutboxDeduplicationDataCleanup`, or come up with shorter alternative names ;)

**Comment by mauroservienti** [comment]
Shouldn't it be on the `configuration.EnableOutbox();`, something like:

```
configuration.EnableOutbox()
    .SetTimeToKeepDeduplicationData( ... )
    .SetFrequencyToRunDeduplicationDataCleanup( ... );
```

**Comment by mauroservienti** [comment]
In the end that config is valid regardless of the persistence used. Another question: shouldn't we do:

```
configuration.EnableOutbox<RavenDB.../NHibernate...>()
```

instead on blindly relying on the `UsePersistence<T>()` config?

**Comment by weralabaj** [comment]
@SzymonPobiega see propositions above for API, I like it.

**Comment by SzymonPobiega** [comment]
@mauroservienti Yes, :+1: for `configuration.EnableOutbox<RavenDB.../NHibernate...>()` but I think it is not doable in V6 era. I guess we'll have to live with your previous proposal.

**Comment by SzymonPobiega** [comment]
@mauroservienti @weralabaj because it touches the code, what should be the process for this change? From NHibernate point of view this would be my maintainer prio job. I guess I'll treat the necessary core changes as maintainer prio too.

**Comment by weralabaj** [comment]
Does that require any core changes if we don't go with `configuration.EnableOutbox<RavenDB.../NHibernate...>(`?

**Comment by mauroservienti** [comment]
Isn't it only core changes? If we want to move to:

```
configuration.EnableOutbox()
    .SetTimeToKeepDeduplicationData( ... )
    .SetFrequencyToRunDeduplicationDataCleanup( ... );
```

**Comment by SzymonPobiega** [comment]
@mauroservienti core (new API) + persisters (handling of the new API)

**Comment by weralabaj** [comment]
Also related https://github.com/Particular/NServiceBus.RavenDB/issues/128.

**Comment by DavidBoike** [comment]
Because of difficulties in API coordination between the Core and NHibernate, there's no good way to structure this API given that we're so close to RC. We'll have to live with it for now.

I would rather leave this issue open, however, to potentially address in NSB Raven V5.

**Comment by mauroservienti** [comment]
Agree to leave this open to remind us that we need to do something about it

**Comment by weralabaj** [comment]
I think this issue is no longer relevant, or if it is, a new one should be created. Since it's been in the backlog for so long it probably is not that important anyway.
