### ISSUE TITLE
Unable to remove expired Outbox records from Raven database

### ISSUE THREAD

**Issue by jpv001** [Particular/NServiceBus.RavenDB#273]
We have a ton of errors in our logs since the last update to the beta, 4.0.0-beta0007.

**Versions**
NServiceBus version=6.0.0-beta0007
NServiceBus.Autofac version=6.0.0-beta0001
NServiceBus.Azure.Transports.WindowsAzureServiceBus version=7.0.0-beta0012
NServiceBus.RavenDB version=4.0.0-beta0007
RavenDB.Client version=3.5.0-rc-35166
WindowsAzure.ServiceBus version=3.3.2

```
NServiceBus.Persistence.RavenDB.RavenDbOutboxStorage+OutboxCleaner Level: Error, Unable to remove expired Outbox records from Raven database. 
```

This is thrown from here: https://github.com/Particular/NServiceBus.RavenDB/blob/release-4.0.0/src/NServiceBus.RavenDB/Outbox/RavenDbOutboxStorage.cs#L94

There isn't any further detail in the logs as to what the underlying exception is. We've also seen that if the RavenDb goes down for any reason this message spams (10-20 times a second) the logs until the endpoint is shutdown or the db comes back up.

**Comment by weralabaj** [comment]
@jpv001 even though at first look you don't see anything interesting in logs, could you please attach the log file, copy the message from here and open a new non-critical support case using the form on this page http://particular.net/support?

**Comment by jpv001** [comment]
@weralabaj This isn't in a production environment as yet and it's not a critical fix for us, is a support ticket still the right way to go for this? If so I'm happy to log one, I'm just checking out the new betas as they come out for compatibility and future use.

**Comment by weralabaj** [comment]
Since it'll be useful to have a look at your logs, etc. I'd say support ticket is the way to go. Just don't raise it as a critical issue :)

**Comment by mauroservienti** [comment]
After digging in to this we identified what was the missing log statement, and the missing connection to the RavenDB server is not shutting the endpoint anymore. Please @jpv001 re-open this issue if you notice something else.
