### ISSUE TITLE
timout message sent to error queue

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RavenDB#282]
I was trying to test some other raven scenario in this https://docs.particular.net/samples/ravendb/simple/?version=Raven_4  and go the below sent to the error queue 

``` xml
<?xml version="1.0"?>
<ArrayOfHeaderInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <HeaderInfo>
    <Key>NServiceBus.ControlMessage</Key>
    <Value>True</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.MessageIntent</Key>
    <Value>Send</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>Timeout.Id</Key>
    <Value>TimeoutDatas/9</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>CorrId</Key>
    <Value />
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.CorrelationId</Key>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.MessageId</Key>
    <Value>911711dd-557a-4973-9424-912df761daf1\37253</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.ExceptionType</Key>
    <Value>System.Exception</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.HelpLink</Key>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.Message</Key>
    <Value>timeout 'TimeoutDatas/9' was concurrently processed.</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.Source</Key>
    <Value>NServiceBus.Core</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.StackTrace</Key>
    <Value>System.Exception: timeout 'TimeoutDatas/9' was concurrently processed.
   at NServiceBus.DispatchTimeoutBehavior.&lt;Invoke&gt;d__1.MoveNext() in C:\Build\src\NServiceBus.Core\DelayedDelivery\TimeoutManager\DispatchTimeoutBehavior.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ReceiveStrategy.&lt;TryProcessMessage&gt;d__7.MoveNext() in C:\Build\src\NServiceBus.Core\Transports\Msmq\ReceiveStrategy.cs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ReceiveWithTransactionScope.&lt;ProcessMessage&gt;d__2.MoveNext() in C:\Build\src\NServiceBus.Core\Transports\Msmq\ReceiveWithTransactionScope.cs:line 85</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.TimeOfFailure</Key>
    <Value>2016-09-19 01:14:51:797236 Z</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.FailedQ</Key>
    <Value>Samples.RavenDB.Server.TimeoutsDispatcher@SILENT</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ProcessingMachine</Key>
    <Value>SILENT</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ProcessingEndpoint</Key>
    <Value>Samples.RavenDB.Server</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>$.diagnostics.hostid</Key>
    <Value>4baa86d22f053a73212b65f088b8a794</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>$.diagnostics.hostdisplayname</Key>
    <Value>SILENT</Value>
  </HeaderInfo>
</ArrayOfHeaderInfo>
```

**Comment by mauroservienti** [comment]
@Particular/ravendb-persistence-maintainers is this the dedup mechanism kicking in?

> System.Exception: timeout 'TimeoutDatas/9' was concurrently processed.

If it is that should not end up in the `error` Q

**Comment by DavidBoike** [comment]
@SimonCropp were you just running that sample straight through? Repetitively? Anything special? (If it sounds like I'm grasping at straws that may be the case.)

**Comment by SimonCropp** [comment]
@DavidBoike I might be related to me running the previous version (nsb 5) of the sample and having leftover sagas/messages. could that contribute?

**Comment by DavidBoike** [comment]
It could explain it but not excuse it - the timeout dispatcher should really not be sending those messages to the error queue no matter what. We'll investigate.

**Comment by DavidBoike** [comment]
@Particular/nservicebus-maintainers:

@SimonCropp found this issue when smoke testing Raven samples, but this seems like it would be a core issue.

The exception is thrown from [this location in DispatchTimeoutBehavior](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/DispatchTimeoutBehavior.cs#L40) when calling `persister.TryRemove()` returns false.

The exception is thrown in the hopes of rolling back the dispatched message (if the transport allows it) but seems to also result in the message moving to the error queue. Is that intentional?

There doesn't seem to be anything Raven can do as it's operating within the persister contract.

**Comment by timbussmann** [comment]
> The exception is thrown in the hopes of rolling back the dispatched message (if the transport allows it) but seems to also result in the message moving to the error queue. Is that intentional?

the intention is to retry the message and on the retry, it should no longer find the timeout and just consume the message here: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/DispatchTimeoutBehavior.cs#L26

for that message to end up in the error queue, it needs to repeatedly:
* find a timeout
* being unable to remove it

(unless retries/timeout manager are disabled and no retries are possible, in that case it would go straight to the errorqueue, but that seems to ok?)

**Comment by andreasohlund** [comment]
Since its [v6 sample ](https://github.com/Particular/docs.particular.net/blob/master/samples/ravendb/simple/Raven_4/Server/packages.config) there should be [retries enabled](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs#L110)?

**Comment by andreasohlund** [comment]
I propose that we remove this as RTM blocker for now since moving failed dispatch requests to error doesn't seem to have high enough impact to block?

**Comment by weralabaj** [comment]
> doesn't seem to have high enough impact

I guess it depends on what causes it. But we can release the version we have now, and see if that issue will persist.

**Comment by WilliamBZA** [comment]
I have a report of this happening in production
