### ISSUE TITLE
Do not store subscriptions by message assembly version

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.RavenDB#286]
RavenDB sub-issue of https://github.com/Particular/PlatformDevelopment/issues/960  
Also related to https://github.com/Particular/NServiceBus/issues/1394

Quite difficult for Raven because the Major version was included in the calculation of the deterministic guid that becomes part of the document id.

Any given endpoint cannot simply convert the entire database worth of subscriptions because there may be other endpoints attached to the same database that haven't been updated. There are also odd situations that could result from endpoints running different versions, and having an old endpoint update the subscription store in such a way that the new endpoint is using its converted subscriptions and is no longer paying attention.

Since this forces us to change the structure of the subscription documents, we might as well also redesign them to not have a collection of subscribers (we originally wanted to for 4.0) as that creates race conditions when multiple endpoints subscribe to the same thing.

The only safe way seems to be to do it on a type-by-type conversion basis, the first time any message of a given type is published.

Please forgive the amazingly awful pseudocode:

```
GetSubscribersFor(Type type)
{
    subscribers = Raven.LoadStartingWith("NewCollectionName/TypeNameGuid");

    if(!subscribers && !conversionForTypeComplete)
    {
        oldSubscribers = Raven.LoadStartingWith("OldCollectionName")
            .LoopThroughPages()
            .FilterInMemory(type);

        subscribers = Convert(oldSubscribers);
        Raven.Store(subscribers);

        conversionForTypeComplete = true;
    }

    return subscribers;
}
```

**Comment by weralabaj** [comment]
One thought - the upgraded endpoints will re-subscribe, can we then also do the transformation?

**Comment by weralabaj** [comment]
BTW does that mean we now only modify query or that we don't change anything for RTM?

**Comment by weralabaj** [comment]
@Particular/ravendb-persistence-maintainers I looked into this issue in more detail today and have a few questions/remarks to confirm:

- since the signature of the method for retrieving subscribers is `public async Task<IEnumerable<Subscriber>> GetSubscriberAddressesForMessage(IEnumerable<MessageType> messageTypes, ContextBag context)` we can't use "LoadStartingWith" or we have to make multiple calls anyway (one per type), is there some neat Raven trick to optimize it?
- given above, the contention for subscriptions is on the save level, correct? is it really that bad given that subscriptions are saved only during endpoint restart? 
- I don't remember why we have the "conversionComplete" flag? Was that supposed to be a field set on the document after conversion?
- when a new subscription request comes in we need to update the old subscriptions, however I don't think it makes sense to also save new subscription in the old format, am I missing some use case?

**Comment by DavidBoike** [comment]
There is a neat Raven trick called lazy loading. The concept isn't all that dissimilar from Tasks.

https://ravendb.net/docs/article-page/3.5/csharp/client-api/session/how-to/perform-operations-lazily

Do a whole bunch of operations with Lazily and then access one of the values to do everything in one roundtrip, or there's the method to eagerly go get them all too.

Even then, this is only when a message has an inheritance hierarchy, so in practice most calls will only include one message type.

Contention is only on save, yes. Although it doesn't happen on endpoint restart, it happens when _other_ endpoints restart, and the more that do, the worse it is. So generally this happens mostly at development time when you start up an entire system at once.

ConversionComplete should be an in-memory ConcurrentDictionary<Type, bool>. The idea is that as an endpoint starting up, you have no idea what shape the database is in, and you can't assume anything by the absence of documents in the new format. (Could mean no subscriptions, could mean conversion hasn't been attempted yet.) So if you load new format and find subscriptions, great! You're done. If you load new format and find nothing, you have to check for old format subscriptions once and attempt conversion. So the next time you query for subscriptions, because of the bool in the dictionary, you can only query new and not worry if you find nothing.

I think we have to save subscriptions in both formats, similar to the last subscribers switch (which was within the same document) because a system could be transitioning from old to new format, and an older endpoint would deserve to know about a new/updated subscriber as well. Unfortunately that means you really can't get rid of contention until the old format becomes unsupported in the next major.

**Comment by mauroservienti** [comment]
> So if you load new format and find subscriptions, great! You're done. If you load new format and find nothing, you have to check for old format subscriptions once and attempt conversion. 

I'd say that we need to check for the old format in any case. Scenarios:

* Endpoint A is old format
* Endpoint B is new format

[A] handles the incoming subscription request, [B] starts up and at publish time converts stuff to new format. The 2 are aligned.
A new subscription requests comes in [B] handles that and writes new and old format, the 2 are aligned.
Another subscriptions comes in [A] handles it, writes only the old format.

[B] at publish time must always check for old and new format misalignment, regardless of the fact that there is something in the new format or not.

I'd say that we can introduce an "ops" flag in the new release that says `ImNotInterestedInBeingBackwordCompatible` 😄

**Comment by DavidBoike** [comment]
Determined in a meeting with Mauro/David/Andreas/Udi this will have to be a breaking change and that we will have to do it as a downtime-required upgrade. Therefore, we can read the database once, convert to a completely new document type, and then never re-query old information. Still need to consider it being an opt-in change.

Changing milestone to V5
