### ISSUE TITLE
Release RC 2

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus.RavenDB#292]
- [x] Smoke test upgrade using pub-sub samples @weralabaj @DavidBoike 
- [x] Smoke test no-downtime upgrade @weralabaj
- [x] Fix release notes @weralabaj
- [x] Push the release to NuGet, announce @weralabaj
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/35xxOtLskkY/TtR0FMdKBgAJ
https://github.com/Particular/NServiceBus.RavenDB/releases/tag/4.0.0-rc2

/cc: @mauroservienti @DavidBoike would be good to double or even triple check that, once https://github.com/Particular/docs.particular.net/pull/1987 gets merged

**Comment by weralabaj** [comment]
@weralabaj update:
- Verified pub-sub:
 - V6 subscribers get events after upgrade, both when running with autosubscibe disabled and enabled
 - if endpoint name changes but queue stays the same, subscription entry is updated
 - V5 endpoints get events even after running V6 endpoints and modifying subscription documents

**Comment by DavidBoike** [comment]
Double-checked this, it all looks good. Was able to go back and forth from V5 to V6 with ease.
