### ISSUE TITLE
Subscription persister does not handle casing correctly

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.RavenDB#307]
Subscription persister in latest version (4.0. and 4.1) does not handle casing when comparing subscriptions: https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/Subscriptions/SubscriptionClient.cs#L24

It should compare `TransportAddress` all lowercase to prevent subscriptions requests coming in with different casing to generate multiple subscriptions.

**Comment by DavidBoike** [comment]
This was fixed in 4.0.2 and 4.1.2
