### ISSUE TITLE
Outbox persister may fail if handling non-CombGuid message id

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.RavenDB#313]
Discovered that for subscription messages, NServiceBus is not assigning a CombGuid message id, and so the transport-native message id ends up getting used for Outbox instead. In the case of MSMQ, the transport-native id is in the form of `{Guid}\{Integer}` and is rejected by RavenDB due to the URL-incompatible `\` character.

Although subscription messages should still have standard CombGuid ids (https://github.com/Particular/NServiceBus/issues/4709) and it's dubious whether control messages should go through the Outbox at all (https://github.com/Particular/NServiceBus/issues/4710) we need to change the Outbox persister to gracefully handle these characters by using character replacement.

### Who's affected

Customers using MSMQ with RavenDB persistence that have also enabled the Outbox and are using Publish/Subscribe are known to be affected because of the MSMQ native message identifiers generated by NServiceBus for subscription messages.

### Symptoms

When a subscription message is received, processing it through the RavenDB Outbox will not succeed because of a `\` character in the subscription message's id, which is incompatible with RavenDB document naming rules. The subscription message will fail to process and be sent to the error queue.

### Backported to

The fix is backported to the following releases:

* 4.1.3 - for RavenDB 3.5 on NServiceBus 6.x
* 4.0.3 - for RavenDB 3.0 on NServiceBus 6.x
* 3.2.1 - for RavenDB 3.5 on NServiceBus 5.x
* 3.0.15 - for RavenDB 3.0 on NServiceBus 5.x

**Comment by DavidBoike** [comment]
As far as priority, I don't see how this could be a data loss scenario. Subscription messages would fail and go to the error queue in a very obvious manner, and we haven't had any reports of this.

**Comment by andreasohlund** [comment]
Agreed on the low prio call, you would have to manually call .Subscribe from a handler to make this fail and v6 removed that option with the new limited IMessageHandlerContext.

That said, what about callback responses? (they are value types transferred as control messages , cc @danielmarbach )

**Comment by DavidBoike** [comment]
@andreasohlund Not quite. This happens on the receive side. The subscription message arrives, Outbox is engaged, and Raven throws because a docId formed from a native MSMQ message id is invalid.

So if you use MSMQ + Raven + Outbox + PubSub you **will** run into this.

**Comment by andreasohlund** [comment]
![giphy 1](https://cloud.githubusercontent.com/assets/125028/26108238/38214a06-3a4c-11e7-88c3-f9b6a871aa74.gif)

**Comment by DavidBoike** [comment]
Able to fix this at only the document persistence layer by replacing `\` with `_` as this is the **only** character that Raven will reject. The property in the message body will still get `\` which means as far as the OutboxMessage class is concerned, nothing has changed - the only change is within the persister class itself. :+1:

I just had a thought though that using `_` as a replacement is a bit arbitrary. Would it make more sense to replace with `/`? Not that I would expect the same system to generate message ids containing `\` vs `_` as the only difference. That would be evil. The argument for `/` is that being another slash it's the "same type of thingie" as `\` ... worth changing?

**Comment by danielmarbach** [comment]
Not sure if anyone or your future self can follow that logic @DavidBoike So for me both seems arbitrary.

**Comment by DavidBoike** [comment]
@danielmarbach Do you have a less arbitrary option or are you just saying that between equally arbitrary options it doesn't really matter?

**Comment by danielmarbach** [comment]
The latter

**Comment by DavidBoike** [comment]
Fixed in patch releases noted in the issue description
