### ISSUE TITLE
Release a RavenDB v3 version once available

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus.RavenDB#34]

**Comment by synhershko** [comment]
I have initiated the process of adding RavenDB 3.0 support to NServiceBus, see https://github.com/Particular/NServiceBus.RavenDB/pull/59

**Comment by synhershko** [comment]
Current state of affairs:

1. The RavenDB 2.5 Client can work with both 2.5 AND 3.0 servers, but a 3.0 client can't talk with a 2.5 server. This is a serious compatibility issue for us, but that's a given and we have to work with it.

2. There are no official docs to support the first previous bullet, I just gathered this info from the mailing list. In #59 I'm working to have the entire test suite of NSB.RavenDB 2.0 to run against both RavenDB 2.5 AND 3.0. If all is green, we can officially support RavenDB 3.0 servers. I will keep you guys posted.

2. We still need to release NSB.RavenDB 3.0 which is compiled against the RavenDB 3.0 client binaries, mostly to support users with endpoints which already upgraded to RavenDB 3.0 (I mean the endpoints themselves; this indeed implies they also running a 3.0 server).

3. The official advise, as I see it, should be: use NSB.RavenDB 2.0 unless you are using the RavenDB server 3.0 yourself, and _everywhere_ in the system, or you are using RavenDB 3.0 and pass DocumentStore / DocumentSession instances to the persisters yourself (e.g. you are using the RavenDB saga persister).

Thoughts? /cc @gbiellem @johnsimons @andreasohlund @SimonCropp

**Comment by SimonCropp** [comment]
Considering the code base in this repo fairly stable I think we should release a new major version that targets raven 3 client. We can still patch the current version

**Comment by andreasohlund** [comment]
+1

**Comment by johnsimons** [comment]
Given our history with Raven compatibility issues between different versions of Client and Server I would stick/enforce v3 for both.

**Comment by synhershko** [comment]
I believe we should do the contrary - NSB.RavenDB 2.0 works so lets not break it, and release a NSB.RavenDB 3.0 which will use 3.0. Then we don't force an upgrade on anyone, but we do give this option.

I'm hesitant about recommending clients to upgrade to RavenDB 3.0 if they can stay on 2.5.

**Comment by johnsimons** [comment]
@synhershko I think we both in agreement.
What I mean is that we have specific versions of NServiceBus.RavenDB lib for each version of RavenDB, so we are going to end up with:
NServiceBus.RavenDB v1 -> RavenDB v2.0 (both client and server)
NServiceBus.RavenDB v2 -> RavenDB v2.5 (both client and server)
NServiceBus.RavenDB v3 -> RavenDB v3.0 (both client and server)

**Comment by SimonCropp** [comment]
-1 for having raven version specific nuget packages. Following this approach will lead to a very long tail of testing, maintenance and support moving forward

**Comment by andreasohlund** [comment]
-1 as well, this would explode the number of permutations we need to support

**Comment by ramonsmits** [comment]
I understand that you do not want to support multiple versions but are there any implications? For example, do users need to update their RavenDB servers or is the RavenDB client lib backwards compatible?

**Comment by johnsimons** [comment]
@ramonsmits the ravendb client would not be backwards compatible.

This is only really an issue if we ever have to patch an old version and that patch needs a breaking change, and because we follow semver, we wouldn't be able to up the major version.
A plausible situation but we haven't yet run into it.

**Comment by Bishbulb** [comment]
I see that the pull request for Raven 3.0 has been reviewed -- is there an unstable build for NServiceBus.RavenDB v3 up on NuGet/MyGet that we could start using for testing? Or alternatively, can someone provide a rough timeline for when v3 support will be officially released?

**Comment by synhershko** [comment]
It's pretty much ready, it's just a matter of stabilizing and releasing a version with the Outbox feature and some more fixes, and then rebase the v3 version on top of that and releasing

**Comment by danielmarbach** [comment]
See PR  #61

**Comment by mauroservienti** [comment]
@danielmarbach what is the status of this? Any ETA on the NuGet package? cheers.

**Comment by danielmarbach** [comment]
It is ready. Doco also updated. Simon already merged it. I planned to wait
another week because I just released 2.2 but essentially you could release
3.0 now if you feel like

Am Montag, 27. April 2015 schrieb Mauro Servienti :

> @danielmarbach <https://github.com/danielmarbach> what is the status of
> this? Any ETA on the NuGet package? cheers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus.RavenDB/issues/34#issuecomment-96512203>
> .
>


-- 

Daniel Marbach

Solution Architect, Particular Software

Email:  daniel.marbach@particular.net

Web:    www.particular.net
<http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba>

**Comment by mauroservienti** [comment]
I have a case asking for it, 1 week is the answer :-)

**Comment by danielmarbach** [comment]
Make it 2

Am Montag, 27. April 2015 schrieb Mauro Servienti :

> I have a case asking for it, 1 week is the answer :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus.RavenDB/issues/34#issuecomment-96520336>
> .
>


-- 

Daniel Marbach

Solution Architect, Particular Software

Email:  daniel.marbach@particular.net

Web:    www.particular.net
<http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba>

**Comment by danielmarbach** [comment]
If they want to live on the edge they can use unstable 3.0 from myget

Am Montag, 27. April 2015 schrieb Mauro Servienti :

> I have a case asking for it, 1 week is the answer :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus.RavenDB/issues/34#issuecomment-96520336>
> .
>


-- 

Daniel Marbach

Solution Architect, Particular Software

Email:  daniel.marbach@particular.net

Web:    www.particular.net
<http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba>

**Comment by mauroservienti** [comment]
link?

On Mon, Apr 27, 2015 at 8:44 AM, Daniel Marbach <notifications@github.com>
wrote:

> If they want to live on the edge they can use unstable 3.0 from myget
>
>
> Am Montag, 27. April 2015 schrieb Mauro Servienti :
>
> > I have a case asking for it, 1 week is the answer :-)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Particular/NServiceBus.RavenDB/issues/34#issuecomment-96520336
> >
> > .
> >
>
>
> --
>
> Daniel Marbach
>
> Solution Architect, Particular Software
>
> Email: daniel.marbach@particular.net
>
> Web: www.particular.net
> <
> http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus.RavenDB/issues/34#issuecomment-96521475>
> .
>



-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by SimonCropp** [comment]
> If they want to live on the edge they can use unstable 3.0 from myget

no

**Comment by jackawatts** [comment]
Hi guys, with @Bishbulb and @mauroservienti have a client testing RavenDB 3.0 but it has broken their NSB implementation (Sagas, Timeouts & Gateway).  Are we still looking at a few days or am I best to orchestrate a roll-back for the time being.
