### ISSUE TITLE
Adding [Unique] to saga property results in duplicate saga entities thus data corruption

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.RavenDB#346]
Assume there is an existing saga data class and that there are saga instances stored in RavenDB. If you now add `[Unique]` to enforce uniqueness and a message is processed with `IAmStartedBy<T>` the existing document for that instance is not used! A *SagaUniqueIdentities* document gets created including an additional new saga instance document!

Logic wise this is expected as the SagaUniqueIdentities document does not exist for the property thus the logic assumes the saga instance document does not exist but that is a false assumption.

This is verified with:

* NServiceBus 4.7.12 / NServiceBus.RavenDB 1.0.7
* NServiceBus 5.2.22 / NServiceBus.RavenDB 3.2.1

## Upgrade from core 5 to 6 extremely vulnerable to corruption

I verified that if you do not have the [Unique] attribute present in core 5, then migrate to 6, that you are extremely vulnerable to this data corruption as core 6 implicitly adds the Uniqueness constraint!

**Comment by DavidBoike** [comment]
This was not possible in V5 without the AllowStaleSagaReads option.

We have updated the information in the upgrade guide to describe this scenario:

https://docs.particular.net/persistence/upgrades/ravendb-3to4#migrate-saga-data-if-using-allowstalesagareads

We are also updating the obsolete message for AllowStaleSagaReads in NServiceBus.RavenDB 4.0.6, 4.1.6, and 4.2.2 to better state the situation and point toward the upgrade guide.
