### ISSUE TITLE
Should the outbox cleaner delay if encountering errors while cleaning?

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RavenDB#354]
Looking at the code it seems like we could enter a tight loop and churn CPU?

https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/Outbox/RavenDbOutboxStorage.cs#L93

Side note: Should the inability to clean raise a critical error?

**Comment by DavidBoike** [comment]
Ah, you're saying vs. having the delay at the beginning of the loop?

It would probably be good for a circuit breaker to be involved in the exception handler, yes.

**Comment by andreasohlund** [comment]
>Ah, you're saying vs. having the delay at the beginning of the loop?

Yea, not sure if this is an issue though. Just saw it when doing https://github.com/Particular/DotNetCoreLaunch/issues/62#issuecomment-334254809

**Comment by danielmarbach** [comment]
As part of the next enhancement release 6.3.0 we provide an ability to opt-in for RavenDB's native document expiration mechanism which should be the preferred approach. We are going to highlight that in the documentation. Closing as won't fix
