### ISSUE TITLE
Synchronized storage session is redundantly added to pipeline

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.RavenDB#365]
When using multiple persistences, the synchronized storage session for RavenDB is configured, even if the Saga/Outbox persistence is not selected.

This configuration throws an exception:

```csharp
endpointConfiguration.UsePersistence<RavenDBPersistence, StorageType.Subscriptions>().SetDefaultDocumentStore(documentStore);
endpointConfiguration.UsePersistence<InMemoryPersistence, StorageType.Sagas>();
endpointConfiguration.UsePersistence<InMemoryPersistence, StorageType.Timeouts>();
endpointConfiguration.UsePersistence<InMemoryPersistence, StorageType.Outbox>();
```

> Unable to cast object of type `NServiceBus.Persistence.RavenDB.RavenDBSynchronizedStorageSession` to type `NServiceBus.InMemorySynchronizedStorageSession`.

In v5 this configuration worked:

```csharp
configuration.UsePersistence<RavenDBPersistence>).SetDefaultDocumentStore(documentStore).For(Storage.Subscriptions);
configuration.UsePersistence<InMemoryPersistence>().For(Storage.Sagas, Storage.Timeouts, Storage.Outbox);
```

I think this was originally introduced here https://github.com/Particular/NServiceBus.RavenDB/pull/154 but I'm not sure why that change was made. Maybe one of the @Particular/ravendb-persistence-maintainers  has the context.

**Comment by mauroservienti** [comment]
I dived into [Slack history](https://particularsoftware.slack.com/archives/C0F8WB2JY/p1452058345000173):

> Let's say that in your endpoint there is a saga defined, than in other handlers you can use the `RavenDbStorageSession`. As you remove the saga from the endpoint all other handlers are broken with NRE

At that time if the endpoint was hosting a saga, the `RavenDbStorageSession` was available to sagas and to all handlers. Removing the saga definition would have stopped the persister to register the `RavenDbStorageSession` in the pipeline causing all handlers immediately to fail. I remember that this was raised by a customer.

**Comment by DavidBoike** [comment]
Current plan is:

* Revert the behavior to original
* Add an opt-in API to `.AlwaysRegisterRavenSharedSession()` so that a user doesn't have to build their own unit of work just to access and use the configured RavenDB database for business data
* Preferably, throw an informative exception guiding users to find the new API rather than just throwing a NRE when attempting to access the storage session without new option enabled
* Document new API

Can this be done in a patch? I worry it's a breaking change that wouldn't be too fun if you're just updating a patch release in a running system.

The alternative is to make current behavior the default and have `.OnlyRegisterRavenSharedSessionWhen…SagaOrOutboxIsInUse()` … the name would clearly need work, but then this wouldn't be a breaking change for current users.

**Comment by mauroservienti** [comment]
It’s a breaking change meaning we need to release a major of RavenDB persistence for NServiceBus V6 and then port to latest on NServiceBus on .NET Core

**Comment by DavidBoike** [comment]
Tried to make a failing test for this but I failed to do so. It looks like it works!

@mikeminutillo could you take a look at [this acceptance test](https://github.com/Particular/NServiceBus.RavenDB/blob/sync-session/src/NServiceBus.RavenDB.AcceptanceTests/When_using_polyglot_persistence.cs) and see if there's anything I missed?

Here's the output of the context on my test run. Looks like it's using all the correct persister types and synchronized storage type, but nothing throws like you indicate.

```
Done = True
SubscriptionsType = NServiceBus.Persistence.RavenDB.SubscriptionPersister
SagasType = NServiceBus.InMemorySagaPersister
OutboxType = NServiceBus.InMemoryOutboxStorage
TimeoutsType = NServiceBus.InMemoryTimeoutPersister
SyncSessionType = NServiceBus.InMemorySynchronizedStorageSession
TestRunId = 1408a509-4b12-4f43-bb26-277102a90dd3
EndpointsStarted = True
HasNativePubSubSupport = False
```

Test is using NSB 6.1.2 and Raven client 3.5.0.

**Comment by janovesk** [comment]
I have a customer getting hit by this. They are migrating away from RavenDB in a step-by-step way. Their plan is to move sagas only to SQLPersistence first. This means RavenDB for everything except Sagas. 
```
var sqlPersistence = endpointConfiguration.UsePersistence<SqlPersistence>();
var ravenDbPersistence = endpointConfiguration.UsePersistence<RavenDBPersistence, StorageType.Subscriptions>(); //any storagetype with RavenDB will lead to exception
```
That combination blows up with: 



```
2017-12-08 09:52:26.452 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '278d0c2d-44cc-40f1-bd0b-a84300923d0d' because of an exception:
System.Exception: The endpoint has not been configured to use SQL persistence.
   at NServiceBus.SqlPersistenceStorageSessionExtensions.GetSqlStorageSession(SynchronizedStorageSession session)
   at SagaPersister.<GetSagaData>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SagaPersister.<Get>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.PropertySagaFinder`1.<Find>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.SagaPersistenceBehavior.<Invoke>d__1.MoveNext()
```
**System.Exception: The endpoint has not been configured to use SQL persistence** is SQL Persistence sagapersistors way of saying the synchronized storage session is not what it expected (It's getting a Raven thingy)

**Comment by janovesk** [comment]
Repro from customer: https://github.com/michaldog/nservicebus_sqlpersistence

**Comment by janovesk** [comment]
You can work around the problem by disabling the RavenDb shared session feature:

```endpointConfiguration.DisableFeature(Type.GetType("NServiceBus.Persistence.RavenDB.RavenDbStorageSession, NServiceBus.RavenDB"));```

**Comment by mikeminutillo** [comment]
@DavidBoike You need to have a saga to ensure that the persistence is getting involved but to get to the problem I just call 

```csharp
var ravenSession = context.SynchronizedStorageSession.RavenSession();
``` 

from within a non-saga handler.

**Comment by DavidBoike** [comment]
@mikeminutillo The acceptance test has a saga in it already, to make sure the saga feature is invoked, and it’s fine. Also I’m confused why you’d call RavenSession at all if Saga and Outbox are configured to use a different persistence?

**Comment by mikeminutillo** [comment]
In other words, the exception is thrown just after the test succeeds.

**Comment by SzymonPobiega** [comment]
FYI in SQLP we are going with the approach of enabling the synchronized session whenever SQL persistence claims responsibility for sagas or outbox concerns, even if they are not activated later. This allows to mix and match persistences safely while maintaining sensible default behavior (I configured SQL persistence for everything therefore I get access to session even if I don't have sagas). More details [here](https://github.com/Particular/NServiceBus.Persistence.Sql/issues/270#issuecomment-391300773)
