### ISSUE TITLE
All storages are required

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RavenDB#38]
So in the core we default to the in-core RavenDB for all storage types https://github.com/Particular/NServiceBus/blob/4.6.5/src/NServiceBus.Core/Persistence/Raven/ConfigureRavenPersistence.cs#L159 

        public static void RegisterDefaults()
        {
            InfrastructureServices.SetDefaultFor<ISagaPersister>(() => Configure.Instance.RavenSagaPersister());
            InfrastructureServices.SetDefaultFor<IPersistTimeouts>(() => Configure.Instance.UseRavenTimeoutPersister());
            InfrastructureServices.SetDefaultFor<IPersistMessages>(() => Configure.Instance.UseRavenGatewayPersister());
            InfrastructureServices.SetDefaultFor<IDeduplicateMessages>(() => Configure.Instance.UseRavenGatewayDeduplication());
            InfrastructureServices.SetDefaultFor<ISubscriptionStorage>(() => Configure.Instance.RavenSubscriptionStorage());
        }

And here https://github.com/Particular/NServiceBus.RavenDB/releases we say to use the new external RavenDB nuget all you need is 

```
Configure.With()
    .DefaultBuilder()
    .RavenDBStorage()
```

However this means that the default for all the other storages  (timeouts, subscriptions etc) will default to the ravendb in the core. which results in 

> "The RavenDB server you have specified is detected to be Product version: 2.5.0 / 6dce79a, Build version: 2916. NServiceBus requires RavenDB version 2.0 to operate correctly. Please update your RavenDB server. Further instructions can be found at:http://particular.net/articles/using-ravendb-in-nservicebus-installing"

The workaround is to fully define all the storages

```
 Configure.With()
            .DefaultBuilder()
            .RavenDBStorage()
            .UseRavenDBSagaStorage()
            .UseRavenDBSubscriptionStorage()
            .UseRavenDBTimeoutStorage()
            .UseRavenDBGatewayDeduplicationStorage()
            .UseRavenDBGatewayStorage()
```

Repro here https://github.com/Particular/BugsRepro/tree/master/RavenDbMissingInjection

**Comment by synhershko** [comment]
@SimonCropp this sounds more like of a docs issue no? what fix did you have in mind?

**Comment by johnsimons** [comment]
The configuration of persistences has been improved in v5 and should not be this confusing anymore.
