### ISSUE TITLE
Create a Raven transport

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RavenDB#44]
Raised by @andreasohlund
Migrated from by https://github.com/Particular/NServiceBus/issues/425

To allow us to run without msmq we should consider creating a RavenDB transport

**Comment by synhershko** [comment]
What's the current stance on this? Is this meant for production use or just for better development story?

Using an eventually consistent database is tricky for transport, unless you'll take care of not hitting the indexes at all and in which case you need to make sure you know which IDs to look for, and custom IDs will reduce the write speeds it is possible to achieve with RavenDB.

**Comment by SimonCropp** [comment]
closing. dont see this as worth the ROI. sorry @andreasohlund
