### ISSUE TITLE
RavenDBPersistence - ConnectionParameters: how to set credentials or an entire connection string?

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.RavenDB#51]
The RavenDBPersistence adds an extension method, SetDefaultDocumentStore, that has an overload that takes a ConnectionParameters instance:

* the name is misleading: ConnectionParameters has nothing to do with DefaultDocumentStore;
* seems that there is no way to set credentials, such as username and password, in the connection parameters, the only supported credential info is the ApiKey;

--

I'm following up a Desk case where the requirement is to manually build, in C#, the connection string and set it at endpoint configuration time. Suggestions?

**Comment by synhershko** [comment]
> I'm following up a Desk case where the requirement is to manually build, in C#, the connection string and set it at endpoint configuration time

Yes, that is the intention. `ConnectionParameters` is a simple object bearing the Url, DatabaseName and optional ApiKey. That is all.

`SetDefaultDocumentStore` will accept a DocumentStore instance, or will create one itself given connection parameters. There's nothing misleading about it - you can set a default DocumentStore without creating the actual instance yourself.

Noted about credentials, will add this now.

Regarding the actual DefaultDocumentStore functionality - it becomes tricky when more features are added over time, see for example my comment in https://github.com/Particular/NServiceBus.RavenDB/pull/43. I move for us to come up with a well defined story and around that and change the API accordingly.

Closing as non-issue.
