### ISSUE TITLE
Error message when trying to use RavenDB 3.0 persistence

### ISSUE THREAD

**Issue by Alainbates** [Particular/NServiceBus.RavenDB#54]
I installed RavenDB 3.0 yesterday and since then, a local NServiceBus app (using RavenDBPersistence) I've been developing has been throwing the following exception.

<i>An exception of type 'System.InvalidOperationException' occurred in NServiceBus.Host.exe but was not handled in user code
Additional information: The RavenDB server you have specified is detected to be Product version: 3.0.0 / cdc39ac / , Build version: 3528. NServiceBus requires RavenDB version 2.5 build 2900 or higher to operate correctly. Please update your RavenDB server.</i>

I see this is because the IsSufficientVersion() method in ConnectionVerifier.cs is hard-coded to only return True when the product version is equal to 2.5. For any newer versions of RavenDB, it will fail and give a confusing error message suggesting that your version of RavenDB needs updating when if anything, it needs downgrading.

**Comment by synhershko** [comment]
This is because we still don't officially support RavenDB 3.0, I have started the process of testing and adding support to it and this should be available soon.

**Comment by johnsimons** [comment]
This has been fix as part of #56
