### ISSUE TITLE
Saga ID has `Guid.Empty` default value after migrating from 5.x to 6.x

### ISSUE THREAD

**Issue by mirmansoor** [Particular/NServiceBus.RavenDB#554]
After conversion of pre-existing Saga data from Raven3.5 to the new SagaDataContainer format, the nested `Data.Id` property is not being set and defaults to empty Guid. This results in the saga having the `Data.Id` property with empty guid.
I suspect [here](https://github.com/Particular/NServiceBus.RavenDB/blob/6b72250c13bfa2b8fe0f32ddef643b54ecf180e2/src/NServiceBus.RavenDB/SagaPersister/UnwrappedSagaListener.cs#L44) we also need to set the `Id` to the `original.Id` after stripping the collection name and extracting the guid part only.

**Comment by DavidBoike** [comment]
@mirmansoor We have been waiting to triage this issue because we don't understand the use case for using the SagaId (which is arbitrary and considered internal to the implementation of RavenDB storage) within the saga message handler. Until you can provide that, either here or within the support case you opened, I'm not sure that we can triage this.

**Comment by ramonsmits** [comment]
Method to patch all already migrated saga documents:

```c#
class SagaDataContainer
{
    public string Id { get; set; }
    public string IdentityDocId { get; set; }
    public IContainSagaData Data { get; set; }

    internal static readonly string SchemaVersion = "1.0.0";
}

static async Task PatchInvalidSagaIdDocuments(IAsyncDocumentSession session)
{
    var query = session.Advanced.AsyncDocumentQuery<SagaDataContainer>(string.Empty)
        .WhereEquals(d => d.Data.Id, Guid.Empty);

    var result = await query.ToListAsync().ConfigureAwait(false);
    foreach (var sagaDataContainer in result)
    {
        await Console.Out.WriteLineAsync($"Patching {sagaDataContainer.Id}");
        sagaDataContainer.Data.Id = Guid.Parse(sagaDataContainer.Id.Substring(sagaDataContainer.Id.IndexOf("/") + 1));
    }
}
```

Note that this isn't a fix! Saga instance not yet migrated will not be patched!

Credit to @mirmansoor for supplying the code that I slightly modified to share here.

**Comment by ramonsmits** [comment]
Resolved in [6.4.1](https://github.com/Particular/NServiceBus.RavenDB/releases/tag/6.4.1) and [6.3.2](https://github.com/Particular/NServiceBus.RavenDB/releases/tag/6.3.2)

**Comment by mirmansoor** [comment]
Thanks @ramonsmits  Just to add to the following point:
> * If the SagaDataContainer is faked like that, it could (maybe?) change the value of the entity type metadata.

Adding the attribute `[JsonProperty(TypeNameHandling = TypeNameHandling.Objects)]` on the derived type of `IContainSagaData` will maintain entity type metadata.

**Comment by ramonsmits** [comment]
The following behavior can be added to ensure invalid timeouts will result in an error so that these can be analyzed and modified in for example ServicePulse.

```c#
//
// Register behavior as follows:
//
//         endpointConfiguration.Pipeline.Register(new ThrowWhenSagaIdHeaderHasEmptyValue(), nameof(ThrowWhenSagaIdHeaderHasEmptyValue));
//
class ThrowWhenSagaIdHeaderHasEmptyValue : Behavior<IIncomingLogicalMessageContext>
{
    static readonly string GuidEmptyValue = Guid.Empty.ToString("D");

    public override Task Invoke(IIncomingLogicalMessageContext context, Func<Task> next)
    {
        var headers = context.Headers;
        var hasSagaIdsHeader = headers.ContainsKey(Headers.SagaId);
        var hasIsTimeoutHeader = headers.ContainsKey(Headers.IsSagaTimeoutMessage);

        if (hasSagaIdsHeader && hasIsTimeoutHeader)
        {
            var headerValue = headers[Headers.SagaId];
            var hasGuidEmptyValue = headerValue == GuidEmptyValue;
            if (hasGuidEmptyValue)
            {
                throw new InvalidOperationException($"Message {context.MessageId} has header {Headers.SagaId} with value '{headerValue}' which must be patched.");
            }
        }

        return next();
    }
}
```
