### ISSUE TITLE
Support for multiple [Unique] attributes on a single saga data instance

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.RavenDB#60]
Currently we enforce that a `ContainsSagaData` instance has only one property decorated with the `Unique` attribute.

**Comment by synhershko** [comment]
This is not RavenDB specific, please raise this in the NServiceBus repo

https://github.com/Particular/NServiceBus/blob/23e83bdbc6c758ea8dae50d329031b60eb93acfc/src/NServiceBus.Core/Saga/UniqueAttribute.cs#L27
