### ISSUE TITLE
Support RavenDB 5.x

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.RavenDB#618]
The current version of NServiceBus.RavenDB is compiled and tested against RavenDB 4.2.

[RavenDB.Client 5 was released in July 2020](https://github.com/Particular/NServiceBus.RavenDB/pull/536). 

- RavenDB FAQ implies that client 4.2 will not be compatible with server 5 https://ravendb.net/docs/article-page/5.0/csharp/client-api/faq/backward-compatibility
- RavenDB API 4 to 5 Client API Migration guide https://ravendb.net/docs/article-page/5.0/csharp/migration/client-api/introduction

**Comment by danielmarbach** [comment]
Further proper [cluster wide transaction support,](https://github.com/Particular/NServiceBus.RavenDB/issues/436) we will need to upgrade to v5.2 or higher of the client

**Comment by danielmarbach** [comment]
Will be released as part of v7 of the persister
