### ISSUE TITLE
How to override TransactionRecoveryStorage?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RavenDB#70]
We set `IsolatedStorageTransactionRecoveryStorage` as default 

https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/Gateway/RavenDbGatewayDeduplication.cs#L42
https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/Timeouts/RavenDbTimeoutStorage.cs#L43
https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/Subscriptions/RavenDbSubscriptionStorage.cs#L43
https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/SessionManagement/RavenDbStorageSession.cs#L47

Which seemed to be initially done in https://github.com/Particular/NServiceBus.RavenDB/issues/28

But in doco we say "dont use IsolatedStorage use LocalDirectory" http://docs.particular.net/nservicebus/ravendb/connecting#transaction-recovery-storage because of this issue https://groups.google.com/forum/#!msg/ravendb/4UHajkua5Q8/ZbsNYv6XkFoJ

However that doco doesnt work since as above we dont do any checks on if the document store was provided by the user. We just override it with `IsolatedStorageTransactionRecoveryStorage`.

            var remoteStorage = store as DocumentStore;
            if (remoteStorage != null)
            {
                remoteStorage.TransactionRecoveryStorage = new IsolatedStorageTransactionRecoveryStorage();
            }

For context that documentation was written here 
https://github.com/Particular/docs.particular.net/commit/eb0648e19e676567be7114d762d62290bd6ed2fb

So i this a bug? or is the documentation wrong?

**Comment by johnsimons** [comment]
It seems to be a bug

**Comment by SimonCropp** [comment]
@johnsimons a bug in the doco or a bug in nsb.raven?

**Comment by SimonCropp** [comment]
@johnsimons and did this ever work? ie is it a regression since that doco was written?

**Comment by johnsimons** [comment]
> a bug in the doco or a bug in nsb.raven?

in the code, it should be supported as stated in the doco

**Comment by johnsimons** [comment]
> did this ever work?

not sure

**Comment by danielmarbach** [comment]
So the code doesn't behave as the doco states it should and I think we shouldn't blindly override it especially not when the user provides it's own document store.

**Comment by DavidBoike** [comment]
Partially fixed by #78 in 3.0.2, will be fully fixed by #136 in 3.1.0, which will carry forward into 4.x.

Closing.

**Comment by SimonCropp** [comment]
@DavidBoike this is not fixed. https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/Internal/TransactionRecoveryStorageVerifier.cs#L19

what if they want to set it to `VolatileOnlyTransactionRecoveryStorage` according to the doco that is supported

**Comment by DavidBoike** [comment]
For CoreV6 this is fixed in #176, for CoreV6 in #164.

Docs update can be found in Particular/docs.particular.net#1253 in which you could even set volatile storage (if you *really* want) using `.CustomizeDocumentStore(Action<IDocumentStore>)`.

**Comment by tmasternak** [comment]
@SimonCropp can you verify based on https://github.com/Particular/NServiceBus.RavenDB/issues/70#issuecomment-193410261 and close if ok?

**Comment by SimonCropp** [comment]
@tmasternak of the prs mentioned one was aborted and not merged and the other is still being dicsussed. So i would say this is not fixed yet

**Comment by mauroservienti** [comment]
@DavidBoike I tried and failed to understand the connection between this and V6 or V5 and the PRs currently open. Need some help :smile:

**Comment by andreasohlund** [comment]
@DavidBoike what's the status here, would we need this for the beta?

**Comment by andreasohlund** [comment]
@Particular/ravendb-persistence-maintainers this is done right? (can we close)

**Comment by DavidBoike** [comment]
OK, current status is that we use IsolatedStorage by default, but if you set it to LocalDirectory (preferred!) we won't mess with that. We also won't mess with anything if you Initialize() your DocumentStore before passing it to us.

The only thing we could potentially uncovered by doco is if you wanted to set Volatile storage (in-memory, very unsafe) for some reason, and did not Initialize() the document store, it would overwrite to IsolatedStorage. Is that worth documenting, and if so, where? Should probably go somewhere within the [main Raven article](http://docs.particular.net/nservicebus/ravendb/) or the one about [setting DTC settings manually](http://docs.particular.net/nservicebus/ravendb/manual-dtc-settings), but I'm not sure where? Suggestions?

**Comment by DavidBoike** [comment]
This is now covered by using your own DocumentStore, which is the preferred method anyway.
