### ISSUE TITLE
RavenUserInstaller exception is misleading

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.RavenDB#75]
When #74 happens the following error is logged:

"ERROR NServiceBus.RavenDB.Persistence.RavenUserInstaller Skipping adding user 'machine\user' to RavenDB, because credentials were provided via connection string"

The reported error has nothing to do with the root cause of the exception as no credentials are provided via the connection string, and the reason of the error is not the connection string.

Source: https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/Internal/RavenUserInstaller.cs#L97

**Comment by danielmarbach** [comment]
Fixed as part of #74
