### ISSUE TITLE
Gateway listener hangs after receiving a message with using NServiceBus.RavenDB v3.01

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.RavenDB#76]
An endpoint that uses the Gateway and RavenDB will hang its http listener when receiving a message via the gateway.

This issue is not occurring in `NServiceBus.RavenDB` v2.2.1

## Reproduction

https://github.com/Particular/docs.particular.net/tree/gateway-ravendb-issue

`samples\gateway\Version_5`

## Package info
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="NServiceBus" version="5.2.3" targetFramework="net45" />
  <package id="NServiceBus.Gateway" version="1.0.0" targetFramework="net45" />
  <package id="NServiceBus.RavenDB" version="3.0.1" targetFramework="net45" />
  <package id="RavenDB.Client" version="3.0.3690" targetFramework="net45" />
</packages>
```

**Comment by DavidBoike** [comment]
When the Gateway receives an HTTP request, it handles it via a Task:

    new Task(() => Handle(context)).Start(scheduler);

Then, the Gateway calls Raven to do its thing and eventually calls `session.SaveChanges()`.

In order for the `InMemoryDocumentSessionOperations` to decide if it should attempt to enlist in a DTC transaction, it eventually (after a few drill-downs) calls:

    public override bool CanEnlistInDistributedTransactions(string dbName)
    {
        return _dtcSupport.GetOrAdd(dbName, db => DatabaseCommands.ForDatabase(db).GetStatistics().SupportsDtc);
    }

What does `GetStatistics()` look like?

In [ServerClient.cs](https://github.com/ravendb/ravendb/blob/15fe034a8611df7fb108d91d6994e5484c8f36ab/Raven.Client.Lightweight/Connection/ServerClient.cs#L410-L413),

		public DatabaseStatistics GetStatistics()
		{
			return asyncServerClient.GetStatisticsAsync().ResultUnwrap();
		}

Then in [AsyncServerClient.cs](https://github.com/ravendb/ravendb/blob/15fe034a8611df7fb108d91d6994e5484c8f36ab/Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs#L1471-L1478):

		public async Task<DatabaseStatistics> GetStatisticsAsync(CancellationToken token = default(CancellationToken))
		{
			using (var request = jsonRequestFactory.CreateHttpJsonRequest(new CreateHttpJsonRequestParams(this, url.Stats(), "GET", credentialsThatShouldBeUsedOnlyInOperationsWithoutReplication, convention)))
			{
				var json = (RavenJObject)await request.ReadResponseJsonAsync().WithCancellation(token).ConfigureAwait(false);
				return json.Deserialize<DatabaseStatistics>(convention);
			}
		}

So we have code in a Task calling a synchronous API that wraps another async Task that's getting ResultUnwrap() called on it. Pretty sure this is an antipattern, and is the whole reason behind the "async all the way down" recommendations. @danielmarbach care to comment?

**Comment by ramonsmits** [comment]
Just stumbled upon this thread : https://groups.google.com/forum/#!topic/ravendb/nm-1iLgGB00

**Comment by ramonsmits** [comment]
Bug in `NServiceBus.Gateway`, have a fix ready
