### ISSUE TITLE
Explicit TransactionRecoveryStorage setting overridden

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.RavenDB#78]
## Who's affected

Anyone who's using NServiceBus.RavenDB and needs to override transaction recovery store

## Symptoms

User creates a custom Raven `DataStore` and explicitly sets the `TransactionRecoveryStorage` property to `LocalDirectoryTransactionRecoveryStorage` but continues to observe exceptions related to Isolated Storage or Non Authoritative Information.

## Analysis

As a part of https://github.com/Particular/NServiceBus.RavenDB/commit/7e235409028191e62bea56350d373dc8561c8fe6 commit, issue #28 (Incorporate DTC fix) has introduced code that is hardcoding `TransactionRecoveryStorage` to `IsolatedStorageTransactionRecoveryStorage` causing to override user specified transaction recovery storage.

This is an issue especially for users that are trying to resolve [transaction recovery issue](http://docs.particular.net/nservicebus/ravendb/connecting#nservicebus-5-other-configuration-options-transaction-recovery-storage) using documented approach. 

## Workaround

Workaround is to drop the class below into the endpoint to restore back `TransactionRecoveryStorage` to `LocalDirectoryTransactionRecoveryStorage` with the desired path.

```c#
public class ShortTermWorkaroundToFixTxRecoveryStoragePath :  IWantToRunWhenConfigurationIsComplete
    {
        public void Run(Configure config)
        {
            var docstore = config.Settings.GetOrDefault<IDocumentStore>("RavenDbDocumentStore") as DocumentStore;
            if (docstore != null)
            {
                docstore.TransactionRecoveryStorage = new LocalDirectoryTransactionRecoveryStorage("C:\\tx_recovery_storage_path");
            }
        }
    }
```

**Desk case**: [11651](https://nservicebus.desk.com/agent/case/11651), [12289](https://nservicebus.desk.com/agent/case/12289)

**Comment by DavidBoike** [comment]
There are 4 code locations that do this. The (false) assumption is that if the IDocumentStore will cast to a DocumentStore, then it was created by NSB and the TransactionRecoveryStorage should be set. 

At the very least we should only overwrite if the existing impl is the volatile tx recovery store. If the isolated storage impl is really this problematic we should consider always setting local directory tx recovery store and using a convention to determine a path in the endpoint directory or perhaps somewhere in AppData.

**Comment by jinskeep** [comment]
This is a problem that we have been encountering lately and it's a somewhat known issue with RavenDB and the resolution from Raven is to use LocalDirectory (https://groups.google.com/forum/#!topic/ravendb/4UHajkua5Q8).

I'll be honest that I'm somewhat hesitant of this as it is classified as the workaround. We have roughly 50+ NSB endpoints right now and will need to implement this workaround on a majority of the endpoints, and then possibly back out the change later when this is "fixed".

**Comment by jinskeep** [comment]
My other observation I'll attach with this is that configuring the LocalDirectory implimentation is pretty cumbersome and causes us to have to manage both the URL and ResourceManagerID manually vs being able to use the infrastructure provided for the default implementation and letting NServiceBus handle the management of these properties.

**Comment by DavidBoike** [comment]
Since the workaround takes advantage of assembly scanning, you could code it as a self-contained, drop-in assembly, and distribute it to your endpoints (most importantly, the ones containing Sagas, I think) like that. Then to back it out of an endpoint, you just have to remove the assembly and then restart the endpoint.

That said, I think the plan is to directly fix this specific bug, and then afterward take additional steps to make it all "just work" without all this tinkering and fussing.
