### ISSUE TITLE
Upgrade to RavenDB.Client 3.0.3785

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RavenDB#80]
Will likely fix https://github.com/Particular/NServiceBus.RavenDB/issues/79

**Comment by danielmarbach** [comment]
Arg. So far about no breaking changes...

**Comment by danielmarbach** [comment]
We have a 3.0.2 in the pipeline by @DavidBoike 
We could up the dependencies there and also update the nuspec. Thoughts?

**Comment by andreasohlund** [comment]
Don't we need to make this a 3.1.0 ?

**Comment by johnsimons** [comment]
How about the server, does it need to be updated too so no incompatabilities between different server/client ?

**Comment by DavidBoike** [comment]
If the server must also be upgraded, then I think 3.0.2 still needs to be released anyway. I have one customer using it as a beta package I sent to them - I need to loop back with them but their silence probably means it's working just fine.

The 3.0.2 change is definitely a needed thing and should be rolled into 3.1 though.

**Comment by kijanawoodard** [comment]
Raven is a server first upgrade. Newer servers talk to older clients, but the reverse is not [always] true.

**Comment by johnsimons** [comment]
> Raven is a server first upgrade. Newer servers talk to older clients, but the reverse is not [always] true.

Another reason to lock in the raven client dependency IMO

**Comment by SimonCropp** [comment]
@johnsimons since locking in the client side nuget range in no way prevents people from talking to a different server version how is this "another reason"?

**Comment by kijanawoodard** [comment]
I have no what it means for versioning this repo, but it seems a [nearly] automated way of producing a new version for each Stable release of raven would be useful. 

For instance, 3785 is the current stable as of last week [iirc] and another should be coming within a few more weeks.

**Comment by johnsimons** [comment]
Good point @SimonCropp, yes it does not enforce the version of Server they use but it does on the Client api which hopefully sends a strong message of what Server they should be on.
We actually enforce the Server version via code, so I guess that would also need to be updated.
This also highlights the requirement of upgrading our Raven Server on our CI agents.

**Comment by johnsimons** [comment]
@kijanawoodard what would be really nice is for Raven Client api to follow semver :wink:

**Comment by kijanawoodard** [comment]
Yes. But then we'd just be talking about moving to Raven Client 13785. ;-)

**Comment by SimonCropp** [comment]
I dont care if Raven DB doesnt follow semver. but the intent of semver is "to communicate the type of change in a given release and the associated risk". I would like to see RavenDB make an attempt to communicate similar information for any given release
