### ISSUE TITLE
Filter out dispatched outbox messages

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.RavenDB#81]
Currently we are not filtering out already dispatched transport operations. This creates unessesary downstream duplicates when a messages id deduped by the outbox.

We should modify

https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/Outbox/OutboxPersister.cs#L45

to only return non dispatched transport operations to prevent this from happening.

In essense we would return an empty list to the core if all the ops have been dispatched

Same as https://github.com/Particular/NServiceBus.NHibernate/issues/118

**Comment by SzymonPobiega** [comment]
Fixing this in a hotfix here https://github.com/Particular/NServiceBus.RavenDB/commit/a1ae660ee51fa8a68324207154a2398fbdbbcb46

@andreasohlund @danielmarbach @Particular/nservicebus please review.
