### ISSUE TITLE
Cleanup is not working

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RavenDB#84]
run the acceptance tests in  dev and raven will use 10+GB

**Comment by SimonCropp** [comment]
seems this is now killing the build http://builds.particular.net/viewLog.html?buildId=124745&buildTypeId=NServiceBusRavenDB_2AcceptanceTests

@danielmarbach @andreasohlund any ideas on how to fix this ?

**Comment by SimonCropp** [comment]
setting a breakpoint here is not fired https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB.AcceptanceTests/Config.cs#L28

**Comment by SimonCropp** [comment]
@danielmarbach ok can u explain to me how this is meant to work https://github.com/Particular/NServiceBus.RavenDB/commit/d1655556ab48970d6d88a8f5c2c2a1edf5f0a281

I can see the cleanup being injected but what is meant to call that?

**Comment by danielmarbach** [comment]
I originally implemented it on develop on the core. After constantly
patching it into RavenDB ATTs I got annoyed with it and removed that
cleanup logic on the 5.2.x acceptance tests in RavenDB. V6 update branch
has it

**Comment by SimonCropp** [comment]
with that in mind i recommend moving develop to v6 now. ATM develop is unusble since running the tests and a few times will max out someone hard drive

**Comment by SimonCropp** [comment]
does master have the same cleanup problem?

**Comment by danielmarbach** [comment]
Yes :( Ok, I merge it in but I need your help to get a few ATTs running

**Comment by andreasohlund** [comment]
Since develop now has the cleanup can we close this one?

**Comment by danielmarbach** [comment]
After we verified that it actually works I'd say yes

**Comment by colin-higgins** [comment]
This was one of those death by a thousand cuts things... The database deletes had chances to fail in many places. I am still not done uncovering them.

**Comment by andreasohlund** [comment]
Is this still an issue?

**Comment by colin-higgins** [comment]
It is less of an issue. The `IDocumentStore` used to cleanup databases for ATT was being disposed of in core. 

This PR fixed that: https://github.com/Particular/NServiceBus.RavenDB/pull/192

There are approximately 250 less databases leaking each time but there are still a couple databases leaking out on each run.

**Comment by DavidBoike** [comment]
Fixed after adding a PowerShell cleanup script ([example here](https://github.com/Particular/NServiceBus.RavenDB/pull/237/commits/3084fc559edc56774e73f7c403ce48aa04761727)) to every active support branch and having TeamCity execute it at the end of every build and acceptance test run.
